version: "3"

services:
  standalone-pulsar:
    image: apachepulsar/pulsar:2.8.1
    ports:
      - "6650:6650"
      - "8080:8080"
    environment:
      - BOOKIE_MEM=" -Xms512m -Xmx512m -XX:MaxDirectMemorySize=1g"
      - transactionCoordinatorEnabled=true
    command: >
      /bin/bash -c
      "bin/apply-config-from-env.py conf/standalone.conf
      && bin/pulsar standalone --advertised-address standalone-pulsar"

  dashboard:
    profiles: [ "dashboard" ]
    image: apachepulsar/pulsar-dashboard
    depends_on:
      - standalone-pulsar
    ports:
      - "80:80"
    environment:
      - SERVICE_URL=http://standalone-pulsar:8080
