addSbtPlugin("com.codecommit"            % "sbt-github-actions"    % "0.14.2")
addSbtPlugin("com.github.sbt"            % "sbt-git"               % "2.0.1")
addSbtPlugin("com.github.sbt"            % "sbt-native-packager"   % "1.10.4")
addSbtPlugin("com.github.sbt.junit"      % "sbt-jupiter-interface" % "0.13.0")
addSbtPlugin("com.lightbend.sbt"         % "sbt-java-formatter"    % "0.8.0")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"          % "0.4.4")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"          % "2.5.2")
