addSbtPlugin("com.codecommit"            % "sbt-github-actions"    % "0.14.2")
addSbtPlugin("com.github.sbt"            % "sbt-git"               % "2.0.1")
addSbtPlugin("com.github.sbt"            % "sbt-native-packager"   % "1.9.13")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"          % "0.3.1")
addSbtPlugin("net.aichler"               % "sbt-jupiter-interface" % "0.11.1")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"          % "2.4.6")
