= Developer Documentation
include::asciidoc/_attributes.adoc[]

`{project-name}` uses xref:https://antora.org/[Antora] to build and compile documentation that is then uploaded to github docs for consumption.

== Structure

Please see link:https://docs.antora.org/antora/latest/standard-directories[structure] documentation for a detailed antora directories and their usage.

A module is a collection of content in a component version that’s related by concept, stage, feature, or other project-specific grouping. While the module does get represented as a URL segment in the published site, it’s primarily an organization tool for the writer. A module cannot be individually configured (meaning it has no metadata of its own).

Current modules

ROOT:: Contains the documentation that is specific to {project-display-name}.

== Local Build

While IntelliJ will have inline viewing per page, sometimes references do not always get pulled in especially from a separate repo.
Developers can validate what they have documented is rendered correctly in context by running antora locally to generate the docs:

[source,bash]
----
npm ci && npx antora antora-playbook.yml --fetch --stacktrace
----
NOTE: Requires `npm` installed and `~/.git-credentials` populated
